apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bv94n9cbx-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bv94n9cbx-dotnet-basic-gitops